# environment.yml
name: crypto-futures-bot
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - ccxt
      - streamlit
      - pandas
      - numpy
      - ta
      - python-telegram-bot
      - schedule
      - requests
      - matplotlib
- name: Copilot deploy
  uses: fuji97/aws-ecs-copilot-deploy@v1.1
- name: Deploy service
  uses: fuji97/aws-ecs-copilot-deploy@v1
  with:
    environments: prod
    workloads: backend frontend
    bucket: my-s3-bucket
    deploy-method: manual
