name: Verify Conda Environment

on:
  push:
    paths:
      - environment.yml
  pull_request:
    paths:
      - environment.yml

jobs:
  setup-conda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: crypto-futures-bot
          environment-file: environment.yml
          python-version: 3.10

      - name: Verify environment
        run: |
          conda info
          conda list
